config/routes.rb
Rails.application.routes.draw do
  root to: "homes#show"
  devise_for :users
  resources :contacts
  namespace :api do
    namespace :v1 do
      resources :contacts, only:[:index, :show]
      resources :users, only:[:index,:show]
    end
  end
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern
  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil) # creates an anonymous scope
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include Filterable
  delegate :full_name, to: :contact_methods
  mount_uploader :image, ContactImageUploader

  # Add validations
  validates :first_name, :last_name, :email, presence: true
  validates_uniqueness_of :email
         
  # Add associations
  belongs_to :user     
  has_many :phones, dependent: :destroy 
  accepts_nested_attributes_for :phones     

  scope :keyword, -> (keyword) { where("first_name LIKE ?", "%#{keyword}%")}  
  #scope :keyword, -> (keyword) { where("last_name LIKE ?", "%#{keyword}%")}         

  def contact_methods
    ContactMethods.new(first_name, last_name, email)
  end

  
end

app/models/contact_methods.rb
class ContactMethods
  attr_reader :first_name, :last_name, :email

  def initialize(first_name, last_name, email)
    @first_name = first_name
    @last_name = last_name
    @email = email
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/name_user.rb
class NameUser
  attr_reader :name, :email, :password, :password_confirmation
  def initialize(name, email, password, password_confirmation)
    @name = name
    @email = email
    @password = password
    @password_confirmation = password_confirmation
  end

  def first_name
    name.split(" ").first
  end

  def last_name
    name.split(' ').drop(1).join(' ')
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  delegate :first_name, :last_name, to: :name_user        
  validates :name, :email, :password, presence: true        
  #Add Associations
  has_many :contacts 

  def name_user
    NameUser.new(name, email, password, password_confirmation)      
  end       
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session

  def index
    render(
      json: Contact.all,
      each_serializer: Api::V1::ContactSerializer
    )
  end
  def show
    contact = Contact.find(params[:id])
    render(json: Api::V1::ContactSerializer.new(contact).to_json)
  end

  def destroy_session
    request.session_options[:skip] = true
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    render(
      json: User.all,
      each_serializer: Api::V1::UserSerializer
    )
  end

  def show
    user = User.find(params[:id])

    render(json: Api::V1::UserSerializer.new(user).to_json)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.filter(filtering_params(params))
  end

  def show
  end

  def new
    @contact = current_user.contacts.new
    2.times do 
      @contact.phones.build
    end
  end

  def edit
  end


  def create
    @contact = current_user.contacts.new(contact_params)
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :image, :group, phones_attributes: [:phone_number])
    end

    def filtering_params(params)
      params.slice(:keyword)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show
    @contacts = Contact.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for @contact, html: { multipart: true }   do |f| %>
      <div class="form-group">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      <%= f.fields_for :phones do |phone_number| %>
        <div class="form-group">
          <%= phone_number.label :phone %>
          <%= phone_number.text_field :phone_number %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :group %><br>
        <%= f.select :group, ['Friends', 'Families', 'Colleagues'] %>
      </div>

        <%= f.submit :class => 'btn btn-primary' %>
    <% end %>
  </div>  
</div>

app/views/contacts/edit.html.erb
<h1>Edit <%= current_user.name %></h1>
<%= render "contacts/form" %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_tag "/contacts", method: :get  do %>
    <%= text_field_tag :keyword, params[:keyword], placeholder: "Keyword" %>
  <%= submit_tag "Search" %>
<% end %>
    <table>
      <thead>
        <tr>
          <th>Image</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= image_tag contact.image.thumb.url %></td>
            <td><%= contact.first_name %></td>
            <td><%= contact.last_name %></td>
            <td><%= contact.email %></td>
            <td><%= link_to 'Show', contact %></td>
            <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
            <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>
<%= render "contacts/form" %>

app/views/contacts/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @contact.image.url %>
</p>
<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>
<p>
  <strong>Phone:</strong>
  <ul>
    <% @contact.phones.each do |phone| %>
      <li><%= phone.phone_number %></li>
    <% end %>  
  </ul>
</p>

<p>
  <strong>Group:</strong>
  <%= @contact.group %>
</p>

<%= link_to 'Back', contacts_path %>
<%= link_to 'Edit', edit_contact_path %>

app/views/homes/show.html.erb
<h1>Contact Nlocal</h1>
<%= form_tag "/contacts", method: :get  do %>
    <%= text_field_tag :keyword, params[:keyword], placeholder: "Keyword" %>
  <%= submit_tag "Search" %>
<% end %> 

<%= @contacts.each do |contact| %>
  <ul>
    <p><%= link_to contact.full_name, contact %></p>
    <p><%= image_tag contact.image.thumb.url %></p>
    <li><%= contact.first_name %></li>
    <li><%= contact.last_name %></li>
    <li><%= contact.email %></li>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "ContactApp", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "New Contact", new_contact_path %></li>
        <% if user_signed_in? %>
          <li><a href="#"><%= current_user.name %></a></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div> 
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManageNlocalContacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <%= render 'shared/alert_messages' %>
  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_alert_messages.html.erb
<% if notice %>
  <p class="alert alert-success" role="alert"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %> 